# Generated by Django 2.2.13 on 2020-06-10 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="gfhgf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_gfhgf",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="hgfjhgfkhf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_hgfjhgfkhf",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="hgjgf",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_hgjgf",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="hjgjhgjh",
            field=models.ManyToManyField(
                blank=True, related_name="customtext_hjgjhgjh", to="home.HomePage"
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="nhgkhghj",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_nhgkhghj",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
