# Generated by Django 2.2.13 on 2020-06-10 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0003_auto_20200610_0738"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="gfhgf",),
        migrations.RemoveField(model_name="customtext", name="hgfjhgfkhf",),
        migrations.RemoveField(model_name="customtext", name="hgjgf",),
        migrations.RemoveField(model_name="customtext", name="hjgjhgjh",),
        migrations.RemoveField(model_name="customtext", name="nhgkhghj",),
        migrations.CreateModel(
            name="Gjhj",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nkjk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gjhj_nkjk",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
