# Generated by Django 2.2.13 on 2020-06-11 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200610_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='fgserhg',
            field=models.ManyToManyField(blank=True, related_name='customtext_fgserhg', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='customtext',
            name='fgsfhgs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_fgsfhgs', to='home.Gjhj'),
        ),
    ]
